name: Movie Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Check code structure
        working-directory: movie-reservation
        run: mvn spotless:check
      - name: Testing with Maven
        working-directory: movie-reservation
        run: mvn test